service: backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"

functions:
  uploader:
    handler: handler.handle
    events:
      - http: POST /upload
    role: UploadRole
    environment:
      BUCKET: napkin-encrypted-storage-${opt:stage, 'dev'}

resources:
  Resources:
    NapkinBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: napkin-encrypted-storage-${opt:stage, 'dev'}
        AccessControl: PublicRead
    UploadRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: upload-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:PutObjectAcl
                  Resource: !Sub
                    - "arn:aws:s3:::${BucketName}/*"
                    - { BucketName: !Ref NapkinBucket }
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    Fn::Sub:
                      - arn:aws:logs:${Region}:${AccountId}:log-group:/aws/lambda/*:*:*
                      - {
                          Region: !Ref AWS::Region,
                          AccountId: !Ref AWS::AccountId,
                        }
